### ISSUE TITLE
Error During executing bot Error

### ISSUE THREAD

**Issue by dsmddsmd** [Widiskel/soniclabs-arcade-bot#6]
![Screenshot_586](https://github.com/user-attachments/assets/bba338ed-27ac-4238-a8d4-e974dc1915d5)

**Comment by copycatcodex** [comment]
It looks like there is an error in your account.js, it says **"You Have 2 Acc but provide 1"**

**Comment by Widiskel** [comment]
Have 2 account but provide 1 proxy
