### ISSUE TITLE
Prerequisite: I've run all the games manually

### ISSUE THREAD

**Issue by QuantumLeap-us** [Widiskel/soniclabs-arcade-bot#9]
![image](https://github.com/user-attachments/assets/6c8a3b24-5207-4cec-97b9-204a35bc52d8)

**Comment by copycatcodex** [comment]
play manual until you get point

**Comment by QuantumLeap-us** [comment]
My smart wallet

**Comment by Joker2701** [comment]
![Screenshot_2](https://github.com/user-attachments/assets/7e0bc719-5121-4f97-a14e-b7255db577aa)
I have the same problem, although I played all the games 10 times, how did you solve this problem?
